### ISSUE TITLE
About Chinese Embedding

### ISSUE THREAD

**Issue by TaoTaoFu** [kichanll/Chinese_Prosody_Predict#1]
Hello Sir, thank you for your sharing.
I searched  the embedding link given in README  and found a file of nearly 7G.
I want to make sure I'm looking right. 

<img width="386" alt="image" src="https://user-images.githubusercontent.com/28522050/116373015-8bfdbc80-a83f-11eb-9be2-5ec83d3e66ac.png">

**Comment by kichanll** [comment]
Hi TaoTaoFu, the tar file is correct. It suitable for your word embedding.

> Hello Sir, thank you for your sharing.
> I searched the embedding link given in README and found a file of nearly 7G.
> I want to make sure I'm looking right.
> 
> <img alt="image" width="386" src="https://user-images.githubusercontent.com/28522050/116373015-8bfdbc80-a83f-11eb-9be2-5ec83d3e66ac.png">

Hi TaoTaoFu, the tar file is correct. It suitable for your word embedding.
